# Generated by Django 3.0.3 on 2020-02-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=128, verbose_name='产品名称')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='用户姓名')),
                ('mobile', models.CharField(blank=True, max_length=128, verbose_name='联系手机')),
                ('company_name', models.CharField(blank=True, max_length=128, verbose_name='单位名称')),
                ('company_domain', models.CharField(blank=True, max_length=128, verbose_name='单位领域')),
                ('company_city', models.CharField(blank=True, max_length=128, verbose_name='单位省市')),
                ('company_address', models.CharField(blank=True, max_length=128, verbose_name='详细地址')),
                ('company_email', models.CharField(blank=True, max_length=128, verbose_name='单位邮箱')),
                ('detail', models.CharField(blank=True, max_length=128, verbose_name='需求描述')),
            ],
        ),
    ]
